In [1]:
import numpy as np

In [18]:
a=np.random.rand(5,5)
a

array([[0.01591078, 0.58333802, 0.24204945, 0.58776692, 0.23171557],
       [0.92519519, 0.77892642, 0.87401195, 0.57607186, 0.70931614],
       [0.42373001, 0.58349853, 0.45634083, 0.79265429, 0.92832953],
       [0.96423154, 0.90359372, 0.13699634, 0.61879971, 0.89919209],
       [0.06609451, 0.11953076, 0.86054588, 0.82501588, 0.96945402]])

In [6]:
type(a)

numpy.ndarray

In [19]:
np.shape(a)

(5, 5)

In [36]:
b=np.random.rand(2,3)
c=np.random.rand(2,3)
np.cross(b,c)

array([[ 0.23414137,  0.29736438, -0.55448047],
       [ 0.20966232,  0.07242873, -0.24773365]])

In [179]:
np.random.randint(10,100,10)

array([81, 43, 42, 20, 58, 23, 42, 87, 67, 89])

In [47]:
import pandas as pd
data=pd.Series([1,2,3,4,5,5,5])
data

0    1
1    2
2    3
3    4
4    5
5    5
6    5
dtype: int64

In [33]:
type(data)

pandas.core.series.Series

In [41]:
import numpy as np
import pandas as pd
dd=np.array([1,2])
dh=pd.Series(dd)
dh

0    1
1    2
dtype: int32

In [48]:
data.drop_duplicates()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [51]:
df=pd.DataFrame({"a":[1,4,7],"b":[2,5,8],"c":[3,6,9]})
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [53]:
df=pd.DataFrame({"a":[1,4,7],"b":[2,5,8],"c":[3,6,9]},index=[1,2,3])
df

   a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [71]:
df1=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['a','b','c'],index=['x','y','z'])
df1

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [59]:
df1['c']

a    3
b    6
c    9
Name: c, dtype: int64

In [60]:
df1.c

a    3
b    6
c    9
Name: c, dtype: int64

In [61]:
df1['a']['b']

4

In [66]:
df1['a']['c']

7

In [67]:
df1.ix['c','a']

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

7

In [73]:
df1.loc['x':'y','a']

x    1
y    4
Name: a, dtype: int64

In [76]:
df1.ix['x','a']=99
df1

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

    a  b  c
x  99  2  3
y   4  5  6
z   7  8  9

In [80]:
df1.ix['x':'z','h']=[9,9,9]
df1

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

    a  b  c  h
x  99  2  3  9
y   4  5  6  9
z   7  8  9  9

In [81]:
df1.describe()

               a    b    c    h
count   3.000000  3.0  3.0  3.0
mean   36.666667  5.0  6.0  9.0
std    54.003086  3.0  3.0  0.0
min     4.000000  2.0  3.0  9.0
25%     5.500000  3.5  4.5  9.0
50%     7.000000  5.0  6.0  9.0
75%    53.000000  6.5  7.5  9.0
max    99.000000  8.0  9.0  9.0

In [82]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 4 columns):
a    3 non-null int64
b    3 non-null int64
c    3 non-null int64
h    3 non-null int64
dtypes: int64(4)
memory usage: 200.0+ bytes

In [88]:
df1.ix['x':'z','i']=9*df1['c']
df1

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

    a  b  c  h   i
x  99  2  3  9  27
y   4  5  6  9  54
z   7  8  9  9  81

In [91]:
df1.to_csv('C:/Users/admin/Desktop/ML/demo.csv',index=False)

In [93]:
data=pd.read_csv('C:/Users/admin/Desktop/ML/demo.csv')
data

    a  b  c  h   i
0  99  2  3  9  27
1   4  5  6  9  54
2   7  8  9  9  81

In [97]:
data=pd.read_excel('C:/Users/admin/Desktop/thekamerastore_prudhvi.xls')
data

,date,hasGoal,hasRevenue,sessionCount,sessions__duration,sessions__deviceCategory,sessions__channel,sessions__activitySummary__PAGEVIEW,sessions__activities__time,sessions_activities_type,sessions_activities_details_Page title,sessions_activities_details_Page URL,sessions__activities__pageTitle
0,2019-05-20,0.0,0.0,1.0,00:00:00,desktop,Referral,1.0,14:54:00,PAGEVIEW,theKameraStore,/,theKameraStore
1,2019-05-19,0.0,0.0,4.0,00:07:00,desktop,Referral,3.0,22:28:00,PAGEVIEW,Nikon Coolpix B500,/product_6.html,Nikon Coolpix B500
2,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22:28:00,PAGEVIEW,Nikon,/nikon,Nikon
3,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22:28:00,PAGEVIEW,theKameraStore,/,theKameraStore
4,NaT,NaN,NaN,NaN,00:17:00,desktop,Referral,7.0,10:46:00,PAGEVIEW,theKameraStore,/index.html,theKameraStore
5,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:46:00,PAGEVIEW,theKameraStore,/index.html,theKameraStore
6,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:46:00,PAGEVIEW,Checkout,/checkout.html,Checkout
7,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:46:00,PAGEVIEW,Cart,/cart.html,Cart
8,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:46:00,PAGEVIEW,Nikon Coolpix W100,/product_8.html,Nikon Coolpix W100
9,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:46:00,PAGEVIEW,Nikon,/nikon,Nikon
10,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:46:00,PAGEVIEW,theKameraStore,/,theKameraStore
11,NaT,NaN,NaN,NaN,00:27:00,desktop,Referral,5.0,09:45:00,PAGEVIEW,Checkout,/checkout.html,Checkout
12,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:45:00,PAGEVIEW,Cart,/cart.html,Cart
13,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:45:00,PAGEVIEW,Coat for Canon EF,/product_b.html,Coat for Canon EF
14,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:45:00,PAGEVIEW,Other Accessories,/accessories,Other Accessories
15,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09:45:00,PAGEVIEW,theKameraStore,/,theKameraStore
16,NaT,NaN,NaN,NaN,01:12:00,desktop,Referral,18.0,00:08:00,PAGEVIEW,theKameraStore,/index.html,theKameraStore
17,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:08:00,PAGEVIEW,Checkout,/checkout.html,Checkout
18,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Cart,/cart.html,Cart
19,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Canon,/canon,Canon
20,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Brand,/brand,Brand
21,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,theKameraStore,/index.html,theKameraStore
22,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,theKameraStore,/index.html,theKameraStore
23,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Brand,/brand,Brand
24,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Fujifilm,/fujifilm,Fujifilm
25,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Fujifilm,/fujifilm,Fujifilm
26,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Canon,/canon,Canon
27,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Fujifilm,/fujifilm,Fujifilm
28,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Fujifilm,/fujifilm,Fujifilm
29,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:07:00,PAGEVIEW,Fujifilm,/fujifilm,Fujifilm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:13:00,PAGEVIEW,theKameraStore,/,theKameraStore
306,2019-05-19,0.0,0.0,1.0,00:18:00,mobile,Direct,2.0,05:17:00,PAGEVIEW,Cart,/cart.html,Cart
307,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05:17:00,PAGEVIEW,theKameraStore,/,theKameraStore
308,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,18:47:00,PAGEVIEW,theKameraStore,/,theKameraStore
309,2019-05-19,0.0,0.0,1.0,00:17:00,mobile,Direct,2.0,12:39:00,PAGEVIEW,theKameraStore,/,theKameraStore
310,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12:39:00,PAGEVIEW,theKameraStore,/,theKameraStore
311,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,09:02:00,PAGEVIEW,theKameraStore,/,theKameraStore
312,2019-05-19,0.0,0.0,1.0,00:32:00,mobile,Direct,2.0,15:07:00,PAGEVIEW,theKameraStore,/index.html,theKameraStore
313,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15:06:00,PAGEVIEW,theKameraStore,/,theKameraStore
314,2019-05-18,0.0,0.0,1.0,00:04:00,mobile,Direct,2.0,22:41:00,PAGEVIEW,Canon,/canon,Canon
315,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22:41:00,PAGEVIEW,theKameraStore,/,theKameraStore
316,2019-05-18,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,23:32:00,PAGEVIEW,theKameraStore,/,theKameraStore
317,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,18:50:00,PAGEVIEW,theKameraStore,/,theKameraStore
318,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,08:34:00,PAGEVIEW,theKameraStore,/,theKameraStore
319,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,21:27:00,PAGEVIEW,theKameraStore,/,theKameraStore
320,2019-05-19,0.0,0.0,1.0,00:31:00,mobile,Direct,3.0,11:21:00,PAGEVIEW,Cart,/cart.html,Cart
321,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11:21:00,PAGEVIEW,Cart,/cart.html,Cart
322,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11:20:00,PAGEVIEW,theKameraStore,/,theKameraStore
323,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,20:27:00,PAGEVIEW,theKameraStore,/,theKameraStore
324,2019-05-19,0.0,0.0,1.0,00:29:00,mobile,Direct,3.0,19:02:00,PAGEVIEW,Cart,/cart.html,Cart
325,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19:02:00,PAGEVIEW,Brand,/brand,Brand
326,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19:02:00,PAGEVIEW,theKameraStore,/,theKameraStore
327,2019-05-18,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,23:57:00,PAGEVIEW,theKameraStore,/,theKameraStore
328,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,10:31:00,PAGEVIEW,theKameraStore,/,theKameraStore
329,2019-05-19,0.0,0.0,1.0,00:00:00,mobile,Direct,1.0,08:34:00,PAGEVIEW,theKameraStore,/,theKameraStore
330,2019-05-19,0.0,0.0,1.0,03:49:00,mobile,Social,5.0,10:29:00,PAGEVIEW,theKameraStore,/index.html,theKameraStore
331,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:27:00,PAGEVIEW,theKameraStore,/,theKameraStore
332,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:25:00,PAGEVIEW,theKameraStore,/,theKameraStore
333,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:25:00,PAGEVIEW,Cart,/cart.html,Cart
334,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10:25:00,PAGEVIEW,theKameraStore,/,theKameraStore

In [140]:
e=[]
o=[]
for i in range(1000):
    if i%2==0:
        e.append(i)
     
    else:
        o.append(i)
df=pd.DataFrame({'even':e,'odd':o})
df.to_csv('C:/Users/admin/Desktop/ML/even&odd1.csv')

In [183]:
ip=pd.DataFrame([[[np.random.rand(20,4)],[np.random.rand(20,1)]]],columns=['input','ouput'],index=range(1,20))
ip

,input,ouput
1,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
2,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
3,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
4,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
5,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
6,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
7,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
8,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
9,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
10,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
11,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
12,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
13,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
14,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
15,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
16,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
17,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
18,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."
19,"[[[0.517387307630147, 0.5117365495154582, 0.71...","[[[0.6323056935888572], [0.6276330773796887], ..."

In [176]:
np.random.rand(20,4)

array([[0.4833799 , 0.99075119, 0.68376838, 0.84840794],
       [0.66551666, 0.73736451, 0.30510925, 0.5644022 ],
       [0.78679195, 0.7666941 , 0.01871801, 0.26201361],
       [0.88428008, 0.39630017, 0.93418093, 0.73882174],
       [0.61452632, 0.36086701, 0.89382584, 0.98646482],
       [0.6437397 , 0.37981161, 0.59225151, 0.26280285],
       [0.06503928, 0.68231884, 0.60726257, 0.88046208],
       [0.12456598, 0.49179269, 0.72724921, 0.1832134 ],
       [0.71346407, 0.43162661, 0.33359513, 0.27373065],
       [0.53899711, 0.97806473, 0.17310995, 0.67487606],
       [0.35422262, 0.12578987, 0.09277067, 0.64228293],
       [0.28004111, 0.03308936, 0.0308882 , 0.67028368],
       [0.28364579, 0.08136071, 0.58239148, 0.00682074],
       [0.31758257, 0.34943708, 0.93688618, 0.35230405],
       [0.09585249, 0.16586735, 0.73446674, 0.5065539 ],
       [0.42659658, 0.19392345, 0.1246948 , 0.60342366],
       [0.02697685, 0.48028059, 0.01855618, 0.5895503 ],
       [0.16786255, 0.99850913, 0.44607874, 0.75606176],
       [0.18447144, 0.36743343, 0.2884965 , 0.72346664],
       [0.33817368, 0.95067193, 0.17534529, 0.29227717]])